name: Generate Commit Snake SVG

on:
  push:
    branches:
      - master  # or your default branch

permissions:
  contents: write

jobs:
  generate-snake-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to count all commits

      - name: Generate yellow-on-black commit snake SVG
        run: |
          commit_count=$(git rev-list --count HEAD)
          width=$((commit_count * 20))
          height=40

          echo '<?xml version="1.0" encoding="UTF-8"?>' > snake.svg
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="'$width'" height="'$height'">' >> snake.svg
          echo '<rect width="'$width'" height="'$height'" fill="black"/>' >> snake.svg

          x=0
          for i in $(seq 1 $commit_count); do
            echo '<rect x="'$x'" y="5" width="18" height="30" fill="yellow" rx="5" ry="5"/>' >> snake.svg
            x=$((x + 20))
          done

          head_x=$(( (commit_count - 1) * 20 + 9 ))
          head_y=20
          echo '<circle cx="'$head_x'" cy="'$head_y'" r="14" fill="yellow"/>' >> snake.svg
          echo '<circle cx="'$((head_x - 5))'" cy="15" r="3" fill="black"/>' >> snake.svg
          echo '<circle cx="'$((head_x + 5))'" cy="15" r="3" fill="black"/>' >> snake.svg
          echo '</svg>' >> snake.svg

      - name: Commit and push SVG to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Switch to output branch or create it if missing
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
          else
            git checkout --orphan output
            git rm -rf .
          fi

          mv snake.svg ./snake.svg
          git add snake.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update commit snake SVG"
            git push origin output --force
          fi
